### ISSUE TITLE
Morning session peer to peer code review

### ISSUE THREAD

**Issue by apt2tell** [Baayeh/todo-list#4]
## To Do List: Code Review

Nice job 👍 Clean code. Excellent!

> We have a few suggestions to make here:
- Your code is neat, but we would rather suggest that you should as much as possible avoid the use of styles in html file. It would rather be better having all styles in <code>style.css</code>
- We also suggest that the use of prettier would improve the code formatting a lot more

**Comment by Baayeh** [comment]
Thanks for the suggestion 👍
